name: dart_week
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  mask: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: mplus
      fonts:
        - asset: assets/fonts/mplus/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus/MPLUS1p-ExtraBold.ttf
          weight: 800
  